name: Puppeteer Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Run Puppeteer
      run: |
        node -e '
          const puppeteer = require("puppeteer");

          (async () => {
            const browser = await puppeteer.launch({ headless: true });
            const page = await browser.newPage();
            await page.goto("https://www.google.com");
            const title = await page.title();
            console.log("Title:", title);
            await browser.close();
          })();
        '
