name: Capture Facebook Signup Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npm install puppeteer
          npx puppeteer browsers install chrome

      - name: Delete existing screenshot
        run: rm -f screenshot.png

      - name: Capture screenshot
        run: |
          node -e "
            const puppeteer = require('puppeteer');

            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://www.facebook.com/r.php');

              await page.waitForSelector('input[name=firstname]');
              await page.type('input[name=firstname]', 'Karim');
              await page.type('input[name=lastname]', 'Elyamani');
              await page.type('input[name=reg_email__]', 'karimfreeg@gmail.com');
              await page.type('input[name=reg_email_confirmation__]', 'karimfreeg@gmail.com');
              await page.type('input[name=reg_passwd__]', 'Karim2021@11');
              await page.select('select[name=birthday_day]', '1');
              await page.select('select[name=birthday_month]', '1');
              await page.select('select[name=birthday_year]', '1999');
              
              await page.click('input._8esa[value="2"]');

              await page.waitForSelector('button[type=submit][name=websubmit]');
              await page.click('button[type=submit][name=websubmit]');

              await page.screenshot({ path: 'screenshot.png', fullPage: true });

              await browser.close();
            })();
          "

      - name: Delete cache and commit logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
