name: Capture Facebook Page Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js from repo
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Capture screenshot
        run: |
          node -e '
          const puppeteer = require("puppeteer");
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto("https://www.facebook.com");
            await page.screenshot({ path: "facebook_screenshot.png" });
            await browser.close();
          })();
          '

      - name: Delete captured screenshot
        run: rm -f facebook_screenshot.png

      - name: Delete cache and commit logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
