name: Capture Facebook Signup Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Install Axios
        run: npm install axios

      - name: Delete existing screenshot
        run: rm -f screenshot.png

      - name: Capture screenshot
        run: |
          node -e "
            const axios = require('axios');
            const puppeteer = require('puppeteer');

            (async () => {
              // Fetching the page content with axios
              const response = await axios.get('https://www.facebook.com/r.php');
              const html = response.data;

              // Loading the page content into Cheerio
              const $ = cheerio.load(html);

              // Finding the element with the given class
              let id = '';
              $('._5k_2 _5dba').each((index, element) => {
                  const attributeValue = $(element).attr('id');
                  if (attributeValue && attributeValue.startsWith('u_0_5')) {
                      id = attributeValue;
                      return false; // Stop iterating after finding the desired ID
                  }
              });

              // Launching Puppeteer and navigating to the page
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://www.facebook.com/r.php');

              // Waiting for the element to be clickable and clicking it
              await page.waitForSelector(\`#\${id}\`);
              await page.click(\`#\${id}\`);

              // Filling the form and submitting it
              await page.waitForSelector('input[name=firstname]');
              await page.type('input[name=firstname]', 'Karim');
              await page.type('input[name=lastname]', 'Elyamani');
              await page.type('input[name=reg_email__]', 'karimfreeg@gmail.com');
              await page.type('input[name=reg_passwd__]', 'Karim2021@11');
              await page.select('select[name=birthday_day]', '1');
              await page.select('select[name=birthday_month]', '1');
              await page.select('select[name=birthday_year]', '1999');
              await page.click('button[type=submit][name=websubmit]');

              // Waiting for navigation to complete
              await page.waitForNavigation();

              // Capturing a full page screenshot
              await page.screenshot({ path: 'screenshot.png', fullPage: true });

              // Getting the final URL and logging it
              const finalUrl = page.url();
              console.log(finalUrl);

              // Closing the browser
              await browser.close();
            })();
          "

      - name: Delete cache and commit logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
