name: node js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Delete existing screenshot
        run: |
          npm install axios cheerio

      - name: Capture screenshot
        run: |
          node yt.js

      - name: Delete cache and commit logs
        run: |
          rm -rf node_modules
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
