name: Capture Facebook Signup Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npx puppeteer browsers install chrome
          npm install puppeteer

      - name: Install Cheerio
        run: npm install cheerio

      - name: Delete existing screenshot
        run: rm -f screenshot.png

      - name: Capture screenshot
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          const cheerio = require('cheerio');

          (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://www.facebook.com/r.php');

              await page.waitForSelector('input[name=firstname]');
              await page.type('input[name=firstname]', 'Karim');
              await page.type('input[name=lastname]', 'Elyamani');
              await page.type('input[name=reg_email__]', 'karimfreeg@gmail.com');
              await page.type('input[name=reg_passwd__]', 'Karim2021@11');
              await page.select('select[name=birthday_day]', '1');
              await page.select('select[name=birthday_month]', '1');
              await page.select('select[name=birthday_year]', '1999');

              const html = await page.content();
              const Ext = cheerio.load(html);
              const id = Ext('._5k_2._5dba').attr('id');
              await page.click(`#${id}`);
              await page.click('button[type=submit][name=websubmit]');
              await page.waitForNavigation();

              const finalUrl = page.url();
              console.log(finalUrl);

              await browser.close();
          })();
          "

      - name: Delete cache and commit logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
