name: node js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Ngrok and configure
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken 2caHmdmIRjB4ANpwvKxjOYuH56N_2NnL8f3pYFBrzTvUVVPzy
          ngrok http https://localhost:8080 &

      - name: Delete existing screenshot
        run: |
          npm install axios cheerio
          npm install express
          rm -rf fb.html
          npm install puppeteer
          npx puppeteer browsers install chrome
          rm -f screenshot.png
          npm install apkpure-scraper-v1

      - name: Capture screenshot
        run: |
          node yt.js

      - name: Delete cache and commit logs
        run: |
          rm -rf node_modules
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update session" --allow-empty)
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
